### ISSUE TITLE
unable to setup on linux

### ISSUE THREAD

**Issue by Dragon0412** [jpn--/larch#15]
作者您好，我正在尝试将larch安装到我的linux系统上，但是无论是我用pip安装，还是用conda，都失败了，请问我应该如何解决？谢谢

**Comment by jpn--** [comment]
不支持使用 pip 安装。您能否提供有关您如何尝试使用 conda 进行安装的更多详细信息？您是否创建了新环境或使用了现有环境？您是否正在从 conda-forge 安装所有依赖项？

**Comment by Dragon0412** [comment]
![image](https://user-images.githubusercontent.com/54929859/144283920-20ff115a-c211-46c2-98ed-13eb2b967db2.png)
我已经安装成功了，可是在运行python程序时还是提示错误
![image](https://user-images.githubusercontent.com/54929859/144284098-2300e248-1e10-4681-b019-f33ce086e610.png)

**Comment by Dragon0412** [comment]
上面的情况是我用
![image](https://user-images.githubusercontent.com/54929859/144284240-362e20bb-3a7a-4d69-8902-de75a279de8f.png)
这个东西来安装的。
当我尝试直接用原生conda来安装larch时，一直都是失败状态

**Comment by Dragon0412** [comment]
请问我直接使用 conda install larch就可以安装了吗
![image](https://user-images.githubusercontent.com/54929859/144284950-4577964e-2918-450a-ac64-5aeb39674295.png)

**Comment by Dragon0412** [comment]
are there any other channels can I get larch by conda command?

**Comment by jpn--** [comment]
[xraylarch](https://github.com/xraypy/xraylarch) is a totally different tool with a similar name.  It's not working because you have installed the wrong "larch".  Try asking for help from the developers of that tool.
