### ISSUE TITLE
Got error when set up Larch

### ISSUE THREAD

**Issue by MengchenZu** [jpn--/larch#2]
Hello,

I have met an error on installing Larch.

When I installed with "pip install larch", I met "could not find a version that satisfies the requirement larch".

And when I clone the source code and installed with "python setup.py install". I got the error on the picture.
![_20180123234420](https://user-images.githubusercontent.com/11532562/35276427-77004d5a-0097-11e8-946d-46159d01027b.jpg)

How can I install Larch?

Best regards,
Mengchen

**Comment by jpn--** [comment]
Unfortunately, I have not had the time or resources to focus on compiling Larch successfully for linux.  You are more than welcome to try, and in theory it should be readily possible, but currently I’ve only gotten around to making versions available on macOS and Windows.  

I am working on a new version of the software that should make cross-platform compilation even easier, but it will be a few months at least before it is ready for use.

_Jeff

**Comment by MengchenZu** [comment]
Thank you. I will have a try on Windows. If there is any problems, I will ask for your help.

Cheers,
Mengchen

**Comment by glederrey** [comment]
Dear Jeff,

Have you been able to work on a new version that is working with Linux? I would be really interested in using and improving larch for stochastic algorithms.

Best,
Gael
