### ISSUE TITLE
LarchError: Weight is only allowed in the idco table

### ISSUE THREAD

**Issue by deepakagrawal** [jpn--/larch#3]
I get this error when I am trying to use weights in the idca format.
```

LarchError: Weight is only allowed in the idco table, but there will be no such
table
```

However, the documentation of the software says we can use weight with idca format.

**Comment by jpn--** [comment]
You can use weights with idca by using idco and idca at the same time. Just create the weights as a single variable idco table. 

_Jeff

**Comment by deepakagrawal** [comment]
I don't understand how can I use both at the same time.
I have a data like 

`

caseid | altid | choice | weight | inv_cost | Time
-- | -- | -- | -- | -- | --
1 | 1 | 1 | 20 | 7 | 1
1 | 2 | 0 | 20 | 5 | 1
1 | 4 | 0 | 20 | 6 | 3
1 | 5 | 0 | 20 | 5 | 4
2 | 1 | 0 | 14 | 7 | 1
2 | 2 | 1 | 14 | 5 | 1
2 | 3 | 0 | 14 | 1 | 2
2 | 4 | 0 | 14 | 6 | 3
3 | 2 | 0 | 2 | 5 | 2
3 | 3 | 1 | 2 | 1 | 2
3 | 5 | 0 | 2 | 6 | 3
3 | 4 | 0 | 2 | 5 | 4
4 | 1 | 0 | 1 | 7 | 1
4 | 2 | 0 | 1 | 5 | 1
4 | 3 | 0 | 1 | 1 | 2
4 | 4 | 1 | 1 | 6 | 3
5 | 1 | 0 | 1 | 7 | 1
5 | 5 | 1 | 1 | 5 | 4

`

while created a larch DB it creates two tables idca with all variables and idco with only weight. How can I write the utility using these? Below is the code I have so far.

`import larch
from larch.roles import P, X, PX

d = larch.DB.CSV_idca("test_small.csv", weight = "weight")
print(d.variables_ca())
m = larch.Model(d)

m.utility.ca = X.weight*(X.inv_cost*P.inv_cost + X.Time*P.Time)

result = m.maximize_loglike()`
