### ISSUE TITLE
in example 301 (itinerary choice) the datafile seems to be missing

### ISSUE THREAD

**Issue by alexmitrani** [jpn--/larch#8]
Referring to this example (and 302)
https://larch.newman.me/example/301_itin_mnl.html

The following line causes a crash:
`d = example(300, 'd')`

> Traceback (most recent call last):
> 
>   File "<ipython-input-183-18d7442e0a12>", line 1, in <module>
>     d = example(300, 'd')
> 
>   File "C:\Users\amitrani\AppData\Local\conda\conda\envs\Python 3.7\lib\site-packages\larch\examples\__init__.py", line 142, in example
>     return _exec_example_n(n, extract=extract, echo=echo)
> 
>   File "C:\Users\amitrani\AppData\Local\conda\conda\envs\Python 3.7\lib\site-packages\larch\examples\__init__.py", line 124, in _exec_example_n
>     f = os.path.join(exampledocdir, get_examplefile(n))
> 
>   File "C:\Users\amitrani\AppData\Local\conda\conda\envs\Python 3.7\lib\site-packages\larch\examples\__init__.py", line 41, in get_examplefile
>     raise UnknownExampleCode(n)
> 
> UnknownExampleCode: 300

Thanks

**Comment by jpn--** [comment]
Should be fixed in version 5.1, release coming momentarily...
